project:
  type: book

book:
  title: "WYMI-BIOS-8010"
  author: "Norah Jones"
  date: "10/28/2023"
  chapters:
    - index.qmd
    - "ws-1.qmd"
    - "ws-2.qmd"
    - "ws-3.qmd"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



